### ISSUE TITLE
Wrong CN in README

### ISSUE THREAD

**Issue by slauriere** [mikefaille/docker-debian-fusiondirectory#2]
Hi Mike,

While giving a try to the image, I ran into an error related to [m-creations/docker-fusiondirectory](https://github.com/m-creations/docker-fusiondirectory) - which was fixed by @rezarahimi (wrong CN in the README): (https://github.com/m-creations/docker-fusiondirectory/issues/2). So I'm posting this note here in case you want to update the [docker-debian-fusiondirectory/README](https://hub.docker.com/r/mikefaille/docker-debian-fusiondirectory/) on Docker Hub  accordingly.

HTH - Cheers

Stéphane

**Comment by mikefaille** [comment]
@slauriere I currently fork himself to my student club repository : https://github.com/ClubCedille/docker-debian-fusiondirectory/tree/1.0.14
and I don't have this problem actually.

You can try it : 

```
git clone -b 1.0.14 https://github.com/clubcedille/docker-debian-fusiondirectory.git
cd docker-debian-fusiondirectory/
docker-compose up
```

**Comment by mikefaille** [comment]
Ho, yes, I must update my README.md. Because, I just want keep this repository for the record, I will had "unmaintened" notice.

Before I forget it : thank you !

**Comment by slauriere** [comment]
Thank you Mike!
